### ISSUE TITLE
Ejercicios (Zahedys)

### ISSUE THREAD

**Issue by YesidBAMO** [CarsOk/corteva_agriscience#10]
carpeta en constante procesó

**Comment by NAYA28cc** [comment]
ejercicios en PSEint 
Operaciones basicas 

	Escribir " ingresa el primer nu mero  "
	Leer  num1
	Escribir  " ingrsa el degundo numero " 
	leer num2 
	
	suma=num1+num2
	resta=num1-num2
	multiplica=num1*num2
	divide=num1/num2
	
	
	Escribir " el resultado de las suma es " suma ;
	Escribir " el resultado de la resta  es " resta ;
	Escribir " el resultado de las multiplicacion es " multiplica ;
	Escribir " el resultado de las divicion  es " divide ;

**Comment by NAYA28cc** [comment]
suma de dimension
[arreglo2.txt](https://github.com/CarsOk/corteva_agriscience/files/8500760/arreglo2.txt)

**Comment by NAYA28cc** [comment]
[ejercicos PSEint.zip](https://github.com/CarsOk/corteva_agriscience/files/8500816/ejercicos.PSEint.zip)
