### ISSUE TITLE
Logo y nombre del APP

### ISSUE THREAD

**Issue by hguzman** [CarsOk/corteva_agriscience#26]
Como: Coordinador académico 
Quiero: Un logo y un nombre para la APP
Para: Tener una mejor presentación  
Criterios de aceptación:
Tiene que tener colores del escudo
Incluir el logo del colegio

**Comment by YesidBAMO** [comment]
![OTRO](https://user-images.githubusercontent.com/99416549/173284343-3cdb3734-ce85-44d5-824d-fbfbf5487e6e.png)
Se adjunta foto del logo
