### ISSUE TITLE
Mackup-Grupo #3

### ISSUE THREAD

**Issue by hguzman** [CarsOk/corteva_agriscience#29]

**Comment by NAYA28cc** [comment]
[Diseño escritorio.docx](https://github.com/CarsOk/corteva_agriscience/files/8894818/Diseno.escritorio.docx)

**Comment by hguzman** [comment]
Se debe cargar en formato PDF, JPG o PNG

**Comment by NAYA28cc** [comment]
[Diseño escritorio.pdf](https://github.com/CarsOk/corteva_agriscience/files/9014405/Diseno.escritorio.pdf)

**Comment by NAYA28cc** [comment]
[actualizacion-diseño.pdf](https://github.com/CarsOk/corteva_agriscience/files/9015424/actualizacion-diseno.pdf)

**Comment by NAYA28cc** [comment]
C:\Users\NATHALIE DAY-TO-DAY\Desktop\ejercicios python\apescritorio.py

**Comment by NAYA28cc** [comment]
[apescritorio.zip](https://github.com/CarsOk/corteva_agriscience/files/9163076/apescritorio.zip)

**Comment by NAYA28cc** [comment]
[apescritorio2.zip](https://github.com/CarsOk/corteva_agriscience/files/9367460/apescritorio2.zip)

**Comment by NAYA28cc** [comment]
[actualizacion mockup.pdf](https://github.com/CarsOk/corteva_agriscience/files/9697411/actualizacion.mockup.pdf)
