### ISSUE TITLE
Diagramas de actividad 

### ISSUE THREAD

**Issue by AdrianaPTC** [CarsOk/corteva_agriscience#32]
Yo: como empresario 
Quiero: tener los diagramas de actividad 
Para: poder saber paso a paso como se realizaran cada requerimientos del proyecto

**Comment by NAYA28cc** [comment]
![image](https://user-images.githubusercontent.com/99416904/228986395-f6045ad6-147b-4b41-a699-b7b221e93728.png)
![image](https://user-images.githubusercontent.com/99416904/228986449-cf2c5a44-17ed-485f-aeb4-de674938d649.png)
![image](https://user-images.githubusercontent.com/99416904/228986478-bda03760-56a8-475d-8427-f9fae450d3f0.png)
![image](https://user-images.githubusercontent.com/99416904/228986522-b8410a79-7f52-46a6-8ead-4776d3afa51a.png)
![image](https://user-images.githubusercontent.com/99416904/228986562-aac0d0a1-567c-48ac-9496-33fbe1afe982.png)
![image](https://user-images.githubusercontent.com/99416904/228986609-6babae8b-8aaa-4b96-b14c-dbc476cf5c54.png)
