### ISSUE TITLE
Diagramas de caso de uso 

### ISSUE THREAD

**Issue by AdrianaPTC** [CarsOk/corteva_agriscience#34]
Yo: como empresario 
Quiero: cuales son todos los diagramas de caso de uso 
Para: saber de forma abreviada todo lo que realizara un requerimiento

**Comment by NAYA28cc** [comment]
![image](https://user-images.githubusercontent.com/99416904/228987976-36d579f9-20f5-4e45-b4d3-d59cee7e77df.png)
![image](https://user-images.githubusercontent.com/99416904/228988002-2e6e0ef4-affa-4678-88c7-59ef395b641e.png)
