### ISSUE TITLE
Normalizacion (zahedys )

### ISSUE THREAD

**Issue by AdrianaPTC** [CarsOk/corteva_agriscience#37]
Como : Empresario 
Quiero: la normalizacion de las tablas de excel 
Para: proteger la integridad de los datos

Criterios de aceptacion 

✓ minimizar la redundancia de los datos 
✓disminuir problemas de actualizacion de los datos de las tablas

**Comment by AdrianaPTC** [comment]
[normalizacion1.xlsx](https://github.com/CarsOk/corteva_agriscience/files/9307678/normalizacion1.xlsx)

1 ejemplo de normalizacion

**Comment by YesidBAMO** [comment]
[miercoles.xlsx](https://github.com/CarsOk/corteva_agriscience/files/9404425/miercoles.xlsx)

**Comment by AdrianaPTC** [comment]
[matricula_aptc.xlsx](https://github.com/CarsOk/corteva_agriscience/files/9405805/matricula_aptc.xlsx)
