### ISSUE TITLE
Base de datos Proyecto

### ISSUE THREAD

**Issue by NAYA28cc** [CarsOk/corteva_agriscience#54]
# Yo como:
Empresario
# Quiero:
Una base de datos
# Para:
 Proyecto

**Comment by Lainerketh** [comment]
Imagen Base de datos
![Sin título](https://user-images.githubusercontent.com/99417108/225649758-fc78d87e-a7e2-4525-8dbf-adb8f502f032.png)

**Comment by Lainerketh** [comment]
actualizacion de la base de dato
![lainer](https://user-images.githubusercontent.com/99417108/227255716-20e52391-d40f-4366-805c-20611e6c60f4.png)
