### ISSUE TITLE
TIMECOP

### ISSUE THREAD

**Issue by NAYA28cc** [CarsOk/corteva_agriscience#56]
# Como:
empresario
# Quiero:
Quiero un excel de mis trabajadores 
# Para:
para llevar un seguimiento de sus horas trabajadas

**Comment by Lainerketh** [comment]
[timecop.csv](https://github.com/CarsOk/corteva_agriscience/files/11052890/timecop.csv)

**Comment by NAYA28cc** [comment]
[semana_20.csv](https://github.com/CarsOk/corteva_agriscience/files/11106438/semana_20.csv)

horas desde 20 marzo hasta 26 marzo
